name: Test Trigger

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [main]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: |
          echo "This is a test workflow to trigger the error summarizer"
          echo "Current time: $(date)"
          echo "Repository: ${{ github.repository }}"
